<a href="https://colab.research.google.com/github/PavloIeremeiew/MachineLearning/blob/main/%D0%84%D1%80%D0%B5%D0%BC%D0%B5%D1%94%D0%B2_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лабораторна робота №1
Варіант2

In [ ]:
import numpy as np
numpy_version = np.__version__
numpy_version


'2.0.2'

1. Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та
виведіть його значення.

In [ ]:
vector = np.arange(1, 21)# заповнює масив числами від 1 до 21 не включно
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його випадковими
натуральними числами та виведіть його значення.

In [ ]:
matrix = np.random.randint(1, 101, (3, 3))# заповнює масив розміром 3 на 3, випадковими числами від 1 до 100
matrix

array([[24, 82, 60],
       [26, 88, 36],
       [19, 57, 17]])

3. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в
діапазоні від -1 до 1 та виведіть його значення

In [ ]:
matrix = np.random.uniform(-1, 1, (5, 5))# заповнює масив розміром 5 на 5, випадковими числами від -1 до 1
matrix = np.round(matrix, 2)# округлення
matrix

array([[ 0.76,  0.75, -0.12,  0.12,  0.15],
       [-0.22, -0.54, -0.58, -0.5 , -0.19],
       [-0.7 , -0.91, -0.23,  0.62, -0.75],
       [-0.56,  0.74,  0.3 , -0.74, -0.41],
       [-0.27, -0.26,  0.3 , -0.72, -0.28]])

4. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть середнє значення елементів.

In [ ]:
matrix = np.random.uniform(0, 1, (5, 5))# заповнює масив розміром 5 на 5, випадковими числами від -1 до 1
matrix = np.round(matrix, 2)# округлення
meanValue = np.mean(matrix)# Обчислення середнього значення елементів

print(matrix)
print()
meanValue

[[0.08 0.87 0.44 0.53 0.22]
 [0.17 0.5  0.63 0.2  0.87]
 [0.87 0.2  0.99 0.67 0.9 ]
 [0.72 0.08 0.83 0.74 0.89]
 [0.19 0.46 0.48 0.58 0.84]]



np.float64(0.5579999999999999)

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими
числами в діапазоні від -10 до 10 та виконайте на них поелементні операції додавання,
віднімання та множення.

In [39]:
array1 = np.random.randint(-10, 11, 5)
array2 = np.random.randint(-10, 11, 5)

# Поелементні операції
sum_result = array1 + array2       # Додавання
diff_result = array1 - array2      # Віднімання
prod_result = np.dot(array1, array2)      # Множення

# Виведення результатів
print("Масив 1:", array1)
print("Масив 2:", array2)
print("Додавання:", sum_result)
print("Віднімання:", diff_result)
print("Множення:", prod_result)

Масив 1: [  9  -6 -10  -2  -7]
Масив 2: [ 7 -1  5  9  7]
Додавання: [16 -7 -5  7  0]
Віднімання: [  2  -5 -15 -11 -14]
Множення: -48


6. Створіть дві матриці 2x2, заповніть їх довільними дійсними числами від 3 до 10 та
знайдіть їх добуток.

In [40]:
array1 = np.random.uniform(3, 11, (2,2))
array1 = np.round(array1, 2)
array2 = np.random.uniform(3, 11, (2,2))
array2 = np.round(array2, 2)

prod_result =  np.dot(array1, array2)     # Множення
prod_result = np.round(prod_result, 2)

# Виведення результатів
print("Масив 1:\n", array1)
print("Масив 2:\n", array2)
print("Множення:\n", prod_result)

Масив 1:
 [[10.87  7.42]
 [ 8.23  6.11]]
Масив 2:
 [[10.81  6.83]
 [ 6.13  7.96]]
Множення:
 [[162.99 133.31]
 [126.42 104.85]]


7. Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 6, (2, 3))
matrix2 = np.random.randint(1, 6, (3, 2))

result_matrix = np.dot(matrix1, matrix2)

print("Матриця 1:\n", matrix1)
print("Матриця 2:\n", matrix2)
print("Результат множення:\n", result_matrix)

Матриця 1:
 [[2 4 5]
 [2 3 4]]
Матриця 2:
 [[5 1]
 [3 1]
 [2 1]]
Результат множення:
 [[32 11]
 [27  9]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 12 та знайдіть її обернену матрицю.

In [ ]:
matrix = np.random.randint(1, 13, (3, 3))

# Перевірка, чи матриця має обернену (визначник не повинен бути нульовим)
if np.linalg.det(matrix) != 0:
    inverse_matrix = np.linalg.inv(matrix)
    inverse_matrix = np.round(inverse_matrix, 2)
else:
    inverse_matrix = "Матриця є виродженою (det=0) і не має оберненої."

print("Матриця:\n", matrix)
print("Обернена матриця:\n", inverse_matrix)

Матриця:
 [[10  7 11]
 [12  5  3]
 [12  2  5]]
Обернена матриця:
 [[-0.05  0.03  0.09]
 [ 0.06  0.22 -0.27]
 [ 0.1  -0.17  0.09]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
діапазоні від -8 до 8 та транспонуйте її.

In [ ]:
matrix = np.random.uniform(-8, 8, (4, 4))
matrix = np.round(matrix, 2)

# Транспонування матриці
transposed_matrix = np.round(matrix.T, 2)


# Виведення матриці та її транспонованої версії
print("Матриця:\n", matrix)
print("Транспонована матриця:\n", transposed_matrix)

Матриця:
 [[-0.81 -0.42 -6.87 -2.13]
 [ 2.06 -3.18 -4.42  0.24]
 [ 2.52  0.86 -4.64  7.41]
 [ 0.08  4.95 -6.62 -0.66]]
Транспонована матриця:
 [[-0.81  2.06  2.52  0.08]
 [-0.42 -3.18  0.86  4.95]
 [-6.87 -4.42 -4.64 -6.62]
 [-2.13  0.24  7.41 -0.66]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть їх випадковими
цілими числами в діапазоні від 1 до 10 та знайдіть середнє значення елементів матриці

In [ ]:
matrix = np.random.randint(1, 11, (3, 4))
vector = np.random.randint(1, 11, (4, 1))

combined_matrix = np.vstack((matrix, vector.T))

mean_value = np.mean(combined_matrix)
matrix,vector, combined_matrix,mean_value

(array([[8, 8, 5, 2],
        [2, 8, 5, 1],
        [3, 3, 5, 6]]),
 array([[ 4],
        [10],
        [ 7],
        [ 5]]),
 array([[ 8,  8,  5,  2],
        [ 2,  8,  5,  1],
        [ 3,  3,  5,  6],
        [ 4, 10,  7,  5]]),
 np.float64(5.125))

11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними
числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [34]:
matrix = np.random.randint(1, 11, (2, 3))

vector = np.random.uniform(0, 1, (3, 1))
vector = np.round(vector, 2)

result = np.dot(matrix, vector)
result = np.round(result, 2)

matrix, vector, result

(array([[ 3, 10,  1],
        [ 4,  8,  7]]),
 array([[0.21],
        [0.55],
        [0.1 ]]),
 array([[6.23],
        [5.94]]))

12. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть їхню різницю.

In [36]:
matrix1 = np.random.randint(1, 11, (3, 3))
matrix2 = np.random.randint(1, 11, (3, 3))

difference = matrix1 - matrix2

matrix1, matrix2, difference

(array([[ 1,  1, 10],
        [ 2,  4, 10],
        [ 7,  6,  3]]),
 array([[ 5, 10,  3],
        [ 3,  3,  5],
        [ 1,  7,  5]]),
 array([[-4, -9,  7],
        [-1,  1,  5],
        [ 6, -1, -2]]))

13. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від -5 до 5 та знайдіть їх добуток.

In [38]:
matrix1 = np.random.randint(-5, 6, (3, 3))
matrix2 = np.random.randint(-5, 6, (3, 3))

result = np.dot(matrix1, matrix2)

matrix1, matrix2, result

(array([[-2,  0, -5],
        [ 0, -1,  5],
        [-5,  0,  3]]),
 array([[ 3,  3,  5],
        [-5,  0, -1],
        [-2,  1, -1]]),
 array([[  4, -11,  -5],
        [ -5,   5,  -4],
        [-21, -12, -28]]))

14. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від -5 до 5 та знайдіть суму елементів матриці.

In [41]:
matrix = np.random.randint(-5, 6, (3, 3))

sum_elements = np.sum(matrix)

matrix, sum_elements

(array([[ 0,  0,  4],
        [-4,  0,  1],
        [ 5, -3,  0]]),
 np.int64(3))

15. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить добуток елементів
кожного рядка матриці.

In [48]:
matrix = np.random.uniform(0, 1, (4, 4))
matrix = np.round(matrix, 2)

row_products = np.prod(matrix, axis=1)

matrix, row_products

(array([[0.95, 0.03, 0.69, 0.39],
        [0.75, 0.47, 0.77, 0.34],
        [0.77, 0.97, 0.86, 0.92],
        [0.09, 0.92, 0.96, 0.18]]),
 array([0.00766935, 0.0922845 , 0.59094728, 0.01430784]))

Висновок: в данній роботі я навчився працювати з матрицями в мові програмування python

Github url: https://github.com/PavloIeremeiew/MachineLearning/blob/main/%D0%84%D1%80%D0%B5%D0%BC%D0%B5%D1%94%D0%B2_%D0%BF%D1%80_1.ipynb